name: HawkEye
main: uk.co.oliwali.HawkEye.HawkEye
authors: [oliverw92, GoalieGuy6, bob7l, ELCHILEN0, stutiguias]
version: 1.6.2
description: Track those griefers like a bird of prey!
dev-url: http://dev.bukkit.org/server-mods/hawkeye-reload/
softdepend: [WorldEdit, HeroChat]
commands:
  hawk:
    description: Track those griefers like a bird of prey!
    aliases: [hawkeye, he, hk, ha]
    usage: /<command> help
permissions:
    hawkeye.*:
        description: Gives access to all HawkEye commands
        default: false
        children:
            hawkeye.search: true
            hawkeye.tpto: true
            hawkeye.rollback: true
            hawkeye.tool: true
            hawkeye.tool.bind: true
            hawkeye.notify: true
            hawkeye.preview: true
            hawkeye.page: true
            hawkeye.rebuild: true
            hawkeye.delete: true
            hawkeye.search.*: true
            hawkeye.writelog: true
            hawkeye.undo: true
            hawkeye.here: true
            hawkeye.help: true
            hawkeye.reload: true
    hawkeye.tool.*:
        description: Permission to use the HawkEye tool
        default: false
        children:
            hawkeye.tool: true
            hawkeye.tool.bind: true
    hawkeye.search.*:
        description: Permission to search all actions
        default: false
        children:
            hawkeye.search.lava-bucket: true
            hawkeye.search.water-bucket: true
            hawkeye.search.item-place: true
            hawkeye.search.pvp-death: true
            hawkeye.search.mob-death: true
            hawkeye.search.other-death: true
            hawkeye.search.command: true
            hawkeye.search.chat: true
            hawkeye.search.join: true
            hawkeye.search.quit: true
            hawkeye.search.door-interact: true
            hawkeye.search.open-container: true
            hawkeye.search.container-transaction: true
            hawkeye.search.item-pickup: true
            hawkeye.search.item-drop: true
            hawkeye.search.button: true
            hawkeye.search.teleport: true
            hawkeye.search.lever: true
            hawkeye.search.sign-place: true
            hawkeye.search.sign-break: true
            hawkeye.search.item-break: true
            hawkeye.search.flint-steel: true
            hawkeye.search.block-place: true
            hawkeye.search.block-break: true
            hawkeye.search.block-burn: true
            hawkeye.search.block-fade: true
            hawkeye.search.block-form: true
            hawkeye.search.leaf-decay: true
            hawkeye.search.mushroom-grow: true
            hawkeye.search.tree-grow: true
            hawkeye.search.water-flow: true
            hawkeye.search.lava-flow: true
            hawkeye.search.explosion: true
            hawkeye.search.enderman-pickup: true
            hawkeye.search.enderman-place: true
            hawkeye.search.entity-kill: true
            hawkeye.search.other: true
            hawkeye.search.spawnmob-egg: true
            hawkeye.search.herochat: true
            hawkeye.search.entity-modify: true
            hawkeye.search.block-inhabit: true
            hawkeye.search.super-pickaxe: true
            hawkeye.search.worldedit-place: true
            hawkeye.search.worldedit-break: true
            hawkeye.search.crop-trample: true
            hawkeye.search.block-ignite: true
            hawkeye.search.fallingblock-place: true
            hawkeye.search.player-water-flow: true
            hawkeye.search.player-lava-flow: true
            hawkeye.search.frame-insert: true
            hawkeye.search.frame-extract: true
            hawkeye.search.container-extract: true
            hawkeye.search.container-insert: true